// <auto-generated />
namespace DatosRC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class cambio_tipo_FechVen : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cambio_tipo_FechVen));
        
        string IMigrationMetadata.Id
        {
            get { return "201604301457087_cambio_tipo_FechVen"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
